In [2]:
import pandas as pd
import numpy as np
import os

In [3]:
gold = pd.read_csv(r"C:\Users\lenovo\Desktop\shivu\gold-currency-dynamics\data\raw\gold_price.csv")

In [4]:
print(f"Data frame shape:----\n{gold.shape}")
print(f"Data-type check:----\n{gold.dtypes}")
print(f"Top 10 rows:----\n{gold.head(10)}")
print(f"Null check:---- \n{gold.isnull().sum()}")
print(f"Data frame summary:----\n{gold.describe()}")

Data frame shape:----
(965, 2)
Data-type check:----
DATE    object
USD     object
dtype: object
Top 10 rows:----
         DATE    USD
0   1/31/1978  207.8
1   2/28/1978  227.3
2   3/31/1978  245.7
3   4/28/1978  242.1
4   5/31/1978  239.2
5   6/30/1978  257.6
6   7/31/1978  279.1
7   8/31/1978  294.7
8   9/29/1978  300.8
9  10/31/1978  355.1
Null check:----
DATE    387
USD     387
dtype: int64
Data frame summary:----
             DATE    USD
count         578    578
unique        578    544
top     1/31/1978  364.2
freq            1      2

In [5]:
#Renaming columns
gold.columns = ["date", "price_usd"]
gold.columns

Index(['date', 'price_usd'], dtype='object')

In [6]:
#Converting data to date-time data type
gold["date"] = pd.to_datetime(gold["date"])
gold.dtypes

date         datetime64[ns]
price_usd            object
dtype: object

In [7]:
#Removing "," from the price to convert all the numbers to the numerics
gold["price_usd"] = gold['price_usd'].str.replace(",", "")
gold["price_usd"] = pd.to_numeric(gold["price_usd"], errors='coerce')

In [8]:
#Checking nulls
print(f"Rechecking nulls: {gold["price_usd"].isna().sum()}")

Rechecking nulls: 387

In [9]:
#Examining the above null values
gold[gold.isna().any(axis=1)]

    date  price_usd
578  NaT        NaN
579  NaT        NaN
580  NaT        NaN
581  NaT        NaN
582  NaT        NaN
..   ...        ...
960  NaT        NaN
961  NaT        NaN
962  NaT        NaN
963  NaT        NaN
964  NaT        NaN

[387 rows x 2 columns]

In [10]:
#Looks like these got added by the additional empty cells
gold = gold.dropna()
#Rechecking
print(f"Null value in date column: {gold["date"].isna().sum()}")
print(f"Null value in colum price_usd: {gold["price_usd"].isna().sum()}")

Null value in date column: 0
Null value in colum price_usd: 0

In [11]:
#Checking duplicates
print(gold.duplicated().any())

False

In [12]:
#Adding year, month and day colums
gold['year'] = gold['date'].dt.year
gold['month'] = gold['date'].dt.month

In [13]:
#Final data
gold

          date  price_usd  year  month
0   1978-01-31      207.8  1978      1
1   1978-02-28      227.3  1978      2
2   1978-03-31      245.7  1978      3
3   1978-04-28      242.1  1978      4
4   1978-05-31      239.2  1978      5
..         ...        ...   ...    ...
573 2025-10-31     4053.3  2025     10
574 2025-11-28     4083.0  2025     11
575 2025-12-31     4289.5  2025     12
576 2026-01-30     4744.5  2026      1
577 2026-02-27     5019.5  2026      2

[578 rows x 4 columns]

In [14]:
gold.to_csv(r"C:\Users\lenovo\Desktop\shivu\gold-currency-dynamics\data\cleaned\gold_clean.csv", index=False)

In [15]:
gold.to_excel(r"C:\Users\lenovo\Desktop\shivu\gold-currency-dynamics\data\cleaned\gold_clean.xlsx", index=False)

**Forex data cleaning**

In [16]:
forex = pd.read_csv(r"C:\Users\lenovo\Desktop\shivu\gold-currency-dynamics\data\raw\fred_exinus-rupee-dollar-value.csv")

In [17]:
print(f"SHAPE:----\n{forex.shape}")
print(f"DATATYPE:----\n{forex.dtypes}")
print(f"NULL VALUES:----\n{forex.isna().sum()}")
print(f"SUMMARY:----\n{forex.describe()}")
forex.head(10)

SHAPE:----
(638, 2)
DATATYPE:----
observation_date     object
EXINUS              float64
dtype: object
NULL VALUES:----
observation_date    0
EXINUS              0
dtype: int64
SUMMARY:----
           EXINUS
count  638.000000
mean    38.441068
std     24.394549
min      7.271900
25%     12.574675
50%     42.192200
75%     54.404675
max     90.902500

  observation_date  EXINUS
0       1973-01-01  8.0041
1       1973-02-01  7.7538
2       1973-03-01  7.5465
3       1973-04-01  7.5462
4       1973-05-01  7.4927
5       1973-06-01  7.2719
6       1973-07-01  7.3510
7       1973-08-01  7.5643
8       1973-09-01  7.7000
9       1973-10-01  7.7271

In [18]:
#Update column name
forex.columns = ["date","inr_per_usd"]
forex.head()

         date  inr_per_usd
0  1973-01-01       8.0041
1  1973-02-01       7.7538
2  1973-03-01       7.5465
3  1973-04-01       7.5462
4  1973-05-01       7.4927

In [19]:
#Date datatype
forex["date"] = pd.to_datetime(forex["date"])
print(forex["date"].dtype)

datetime64[ns]

In [20]:
#Converting inr_per_usd to numeric and cheking nulls 
forex["inr_per_usd"] = pd.to_numeric(forex["inr_per_usd"], errors='coerce')
print(forex.isna().sum())

date           0
inr_per_usd    0
dtype: int64

In [21]:
#Checking duplicate values
print(f"Duplicate values:{forex.duplicated().any()}")
print(forex.duplicated(subset=["date", "inr_per_usd"], keep=False).sum())

Duplicate values:False
0

In [22]:
forex = forex.sort_values("date").reset_index(drop=True)

In [23]:
forex

          date  inr_per_usd
0   1973-01-01       8.0041
1   1973-02-01       7.7538
2   1973-03-01       7.5465
3   1973-04-01       7.5462
4   1973-05-01       7.4927
..         ...          ...
633 2025-10-01      88.3691
634 2025-11-01      88.8444
635 2025-12-01      90.0350
636 2026-01-01      90.9025
637 2026-02-01      90.7458

[638 rows x 2 columns]

In [24]:
forex.to_csv(r"C:\Users\lenovo\Desktop\shivu\gold-currency-dynamics\data\cleaned\forex_cleaned.csv", index=False)

In [25]:
forex.to_excel(r"C:\Users\lenovo\Desktop\shivu\gold-currency-dynamics\data\cleaned\forex_cleaned.xlsx", index=False)

**Fred funds cleaning**

In [26]:
    fed_intrest = pd.read_csv(r"C:\Users\lenovo\Desktop\shivu\gold-currency-dynamics\data\raw\fred_fedfunds-fed-intrests.csv")

In [27]:
#General details
print(f"number of rows:----\n{fed_intrest.shape[0]}")
print(f"number of columns:----\n{fed_intrest.shape[1]}")
print(f"Top 10 rows:----\n{fed_intrest.head(10)}")
print(f"datatype check:----\n{fed_intrest.dtypes}")
print(f"null checks:----\n{fed_intrest.isna().sum()}")
print(f"duplicate checks:----\n{fed_intrest.duplicated().sum()}")
print(f"summary of the data:----\n{fed_intrest.describe()}")

number of rows:----
860
number of columns:----
2
Top 10 rows:----
  observation_date  FEDFUNDS
0       1954-07-01      0.80
1       1954-08-01      1.22
2       1954-09-01      1.07
3       1954-10-01      0.85
4       1954-11-01      0.83
5       1954-12-01      1.28
6       1955-01-01      1.39
7       1955-02-01      1.29
8       1955-03-01      1.35
9       1955-04-01      1.43
datatype check:----
observation_date     object
FEDFUNDS            float64
dtype: object
null checks:----
observation_date    0
FEDFUNDS            0
dtype: int64
duplicate checks:----
0
summary of the data:----
         FEDFUNDS
count  860.000000
mean     4.601558
std      3.539090
min      0.050000
25%      1.910000
50%      4.305000
75%      6.122500
max     19.100000

In [28]:
#column rename
fed_intrest.columns = ["date", "fed_intrest_rate"]
fed_intrest.columns

Index(['date', 'fed_intrest_rate'], dtype='object')

In [29]:
#fix datatypes
fed_intrest.dtypes
fed_intrest["date"] = pd.to_datetime(fed_intrest["date"])
fed_intrest.dtypes

date                datetime64[ns]
fed_intrest_rate           float64
dtype: object

In [30]:
#Null check
fed_intrest.isna().sum()

date                0
fed_intrest_rate    0
dtype: int64

In [31]:
#Duplicate check
print(f"count of duplicates: {fed_intrest.duplicated().sum()}")

count of duplicates: 0

In [32]:
#Sorting on date
fed_intrest = fed_intrest.sort_values("date").reset_index(drop=True)

In [33]:
fed_intrest.head()

        date  fed_intrest_rate
0 1954-07-01              0.80
1 1954-08-01              1.22
2 1954-09-01              1.07
3 1954-10-01              0.85
4 1954-11-01              0.83

In [34]:
fed_intrest.to_csv(r"C:\Users\lenovo\Desktop\shivu\gold-currency-dynamics\data\cleaned\cleaned_fed_intrest.csv", index=False)

In [35]:
fed_intrest.to_excel(r"C:\Users\lenovo\Desktop\shivu\gold-currency-dynamics\data\cleaned\cleaned_fed_intrest.xlsx", index=False)

**Inflation**

In [36]:
cpi = pd.read_csv(r"C:\Users\lenovo\Desktop\shivu\gold-currency-dynamics\data\raw\fred_cpi-inflation.csv")

In [37]:
print(f"row count:--- {cpi.shape[0]}")
print(f"top 10 rows:----\n{cpi.head(10)}")
print(f"datatype check:----\n{cpi.dtypes}")
print(f"null values check:----\n{cpi.isna().sum()}")
print(f"duplicate check:----\n{cpi.duplicated().sum()}")
print(f"summary of the data:----\n{cpi.describe()}")

row count:--- 950
top 10 rows:----
  observation_date  CPIAUCSL
0         1/1/1947     21.48
1         2/1/1947     21.62
2         3/1/1947     22.00
3         4/1/1947     22.00
4         5/1/1947     21.95
5         6/1/1947     22.08
6         7/1/1947     22.23
7         8/1/1947     22.40
8         9/1/1947     22.84
9        10/1/1947     22.91
datatype check:----
observation_date     object
CPIAUCSL            float64
dtype: object
null values check:----
observation_date    0
CPIAUCSL            1
dtype: int64
duplicate check:----
0
summary of the data:----
         CPIAUCSL
count  949.000000
mean   124.276411
std     89.605949
min     21.480000
25%     32.850000
50%    109.700000
75%    200.700000
max    327.460000

In [38]:
#Cloumn rename
cpi.columns = ["date", "cpi_index"]
cpi.columns

Index(['date', 'cpi_index'], dtype='object')

In [39]:
#Fix Date datatype
cpi["date"] = pd.to_datetime(cpi["date"])
cpi.dtypes

date         datetime64[ns]
cpi_index           float64
dtype: object

In [40]:
#Fix null value
cpi[cpi.isna().any(axis=1)]
print(cpi[cpi.isna().any(axis=1)])
cpi["cpi_index"] = cpi["cpi_index"].ffill()
print(cpi[cpi.isna().any(axis=1)])

          date  cpi_index
945 2025-10-01        NaN
Empty DataFrame
Columns: [date, cpi_index]
Index: []

In [41]:
#Calculating year-over-year infliation rate
cpi["inflation_yoy"] = cpi["cpi_index"].pct_change(periods=12)*100
cpi["inflation_yoy"]

0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
         ...
945    2.729136
946    2.696444
947    2.653304
948    2.391201
949    2.434004
Name: inflation_yoy, Length: 950, dtype: float64

In [42]:
cpi = cpi.dropna()

In [43]:
cpi

          date  cpi_index  inflation_yoy
12  1948-01-01     23.680      10.242086
13  1948-02-01     23.670       9.481961
14  1948-03-01     23.500       6.818182
15  1948-04-01     23.820       8.272727
16  1948-05-01     24.010       9.384966
..         ...        ...            ...
945 2025-10-01    324.245       2.729136
946 2025-11-01    325.063       2.696444
947 2025-12-01    326.031       2.653304
948 2026-01-01    326.588       2.391201
949 2026-02-01    327.460       2.434004

[938 rows x 3 columns]

In [44]:
cpi.to_csv(r"C:\Users\lenovo\Desktop\shivu\gold-currency-dynamics\data\cleaned\cleaned_cpi_inflation.csv", index=False)

In [45]:
cpi.to_excel(r"C:\Users\lenovo\Desktop\shivu\gold-currency-dynamics\data\cleaned\cleaned_cpi_inflation.xlsx", index=False)

**Merging all cleaned data**

In [46]:
gold = pd.read_csv(r"C:\Users\lenovo\Desktop\shivu\gold-currency-dynamics\data\cleaned\gold_clean.csv", parse_dates=["date"])
forex = pd.read_csv(r"C:\Users\lenovo\Desktop\shivu\gold-currency-dynamics\data\cleaned\forex_cleaned.csv", parse_dates=["date"])
fed = pd.read_csv(r"C:\Users\lenovo\Desktop\shivu\gold-currency-dynamics\data\cleaned\cleaned_fed_intrest.csv", parse_dates=["date"])
inflation = pd.read_csv(r"C:\Users\lenovo\Desktop\shivu\gold-currency-dynamics\data\cleaned\cleaned_cpi_inflation.csv", parse_dates=["date"])

In [47]:
#Checking
print(f"Gold:----\n{gold.head()}")
print(f"Forex:----\n{forex.head()}")
print(f"Fed:----\n{fed.head()}")
print(f"CPI/Inflation:----\n{inflation.head()}")

Gold:----
        date  price_usd  year  month
0 1978-01-31      207.8  1978      1
1 1978-02-28      227.3  1978      2
2 1978-03-31      245.7  1978      3
3 1978-04-28      242.1  1978      4
4 1978-05-31      239.2  1978      5
Forex:----
        date  inr_per_usd
0 1973-01-01       8.0041
1 1973-02-01       7.7538
2 1973-03-01       7.5465
3 1973-04-01       7.5462
4 1973-05-01       7.4927
Fed:----
        date  fed_intrest_rate
0 1954-07-01              0.80
1 1954-08-01              1.22
2 1954-09-01              1.07
3 1954-10-01              0.85
4 1954-11-01              0.83
CPI/Inflation:----
        date  cpi_index  inflation_yoy
0 1948-01-01      23.68      10.242086
1 1948-02-01      23.67       9.481961
2 1948-03-01      23.50       6.818182
3 1948-04-01      23.82       8.272727
4 1948-05-01      24.01       9.384966

In [48]:
#Converting YYYY-MM-DD to YYYY-MM for gold and forex as gold dates are not standard
gold["month_key"] = gold["date"].dt.to_period("M")
forex["month_key"] = forex["date"].dt.to_period("M")

In [49]:
#Recheck
print(f"Gold:----\n{gold.head()}")
print(f"Forex:----\n{forex.head()}")

Gold:----
        date  price_usd  year  month month_key
0 1978-01-31      207.8  1978      1   1978-01
1 1978-02-28      227.3  1978      2   1978-02
2 1978-03-31      245.7  1978      3   1978-03
3 1978-04-28      242.1  1978      4   1978-04
4 1978-05-31      239.2  1978      5   1978-05
Forex:----
        date  inr_per_usd month_key
0 1973-01-01       8.0041   1973-01
1 1973-02-01       7.7538   1973-02
2 1973-03-01       7.5465   1973-03
3 1973-04-01       7.5462   1973-04
4 1973-05-01       7.4927   1973-05

In [50]:
#Merging gold and forex
master = pd.merge(gold, forex, on='month_key', how='inner')

In [51]:
#Dropping non used columns, Rename and aliging columns
master = master.drop(["date_x", "year", "month"], axis=1)
master = master.rename(columns={"date_y":"date"})
master = master[["date", "price_usd", "inr_per_usd", "month_key"]]

In [52]:
master["gold_price_inr"] = master["price_usd"] * master["inr_per_usd"]

In [53]:
master.head()

        date  price_usd  inr_per_usd month_key  gold_price_inr
0 1978-01-01      207.8       8.2010   1978-01      1704.16780
1 1978-02-01      227.3       8.1094   1978-02      1843.26662
2 1978-03-01      245.7       8.2078   1978-03      2016.65646
3 1978-04-01      242.1       8.4650   1978-04      2049.37650
4 1978-05-01      239.2       8.5827   1978-05      2052.98184

In [54]:
fed['month_key'] = fed['date'].dt.to_period("M")
inflation['month_key'] = inflation['date'].dt.to_period("M")

In [55]:
print(fed.head())
print(inflation.head())

        date  fed_intrest_rate month_key
0 1954-07-01              0.80   1954-07
1 1954-08-01              1.22   1954-08
2 1954-09-01              1.07   1954-09
3 1954-10-01              0.85   1954-10
4 1954-11-01              0.83   1954-11
        date  cpi_index  inflation_yoy month_key
0 1948-01-01      23.68      10.242086   1948-01
1 1948-02-01      23.67       9.481961   1948-02
2 1948-03-01      23.50       6.818182   1948-03
3 1948-04-01      23.82       8.272727   1948-04
4 1948-05-01      24.01       9.384966   1948-05

In [56]:
fed_monthly = fed.drop_duplicates(subset="month_key", keep="last")[['month_key', 'fed_intrest_rate']]
inflation_monthly = inflation.drop_duplicates(subset="month_key", keep="last")[["month_key", "inflation_yoy"]]

In [57]:
print(fed_monthly.head())
print(inflation_monthly.head())

  month_key  fed_intrest_rate
0   1954-07              0.80
1   1954-08              1.22
2   1954-09              1.07
3   1954-10              0.85
4   1954-11              0.83
  month_key  inflation_yoy
0   1948-01      10.242086
1   1948-02       9.481961
2   1948-03       6.818182
3   1948-04       8.272727
4   1948-05       9.384966

In [58]:
#Merge fed and inflation with master
master = master.merge(fed_monthly, on='month_key', how='left')
master = master.merge(inflation_monthly, on="month_key", how="left")

In [59]:
#dropping month_key column
master = master.drop(columns=["month_key"])

In [60]:
#Adding calculated columns
master["gold_return_1d"] = master["price_usd"].pct_change() * 100
master["inr_change_1d"] = master["inr_per_usd"].pct_change() * 100
master["gold_inr_return_1d"] = master["gold_price_inr"].pct_change() * 100

In [61]:
master.head()

,date,price_usd,inr_per_usd,gold_price_inr,fed_intrest_rate,inflation_yoy,gold_return_1d,inr_change_1d,gold_inr_return_1d
0,1978-01-01,207.8,8.2010,1704.16780,6.70,6.814310,NaN,NaN,NaN
1,1978-02-01,227.3,8.1094,1843.26662,6.78,6.239460,9.384023,-1.116937,8.162273
2,1978-03-01,245.7,8.2078,2016.65646,6.79,6.375839,8.095029,1.213407,9.406661
3,1978-04-01,242.1,8.4650,2049.37650,6.89,6.500000,-1.465201,3.133605,1.622490
4,1978-05-01,239.2,8.5827,2052.98184,7.36,7.142857,-1.197852,1.390431,0.175924

In [62]:
#Saving the file
master.to_csv(r"C:\Users\lenovo\Desktop\shivu\gold-currency-dynamics\data\cleaned\gold_investment_master.csv", index=False)
print(f"Master data set {master.shape[0]} rows and {master.shape[1]} coloumns")
print(master.columns.to_list())
print(master.head())

Master data set 578 rows and 9 coloumns
['date', 'price_usd', 'inr_per_usd', 'gold_price_inr', 'fed_intrest_rate', 'inflation_yoy', 'gold_return_1d', 'inr_change_1d', 'gold_inr_return_1d']
        date  price_usd  inr_per_usd  gold_price_inr  fed_intrest_rate  \
0 1978-01-01      207.8       8.2010      1704.16780              6.70
1 1978-02-01      227.3       8.1094      1843.26662              6.78
2 1978-03-01      245.7       8.2078      2016.65646              6.79
3 1978-04-01      242.1       8.4650      2049.37650              6.89
4 1978-05-01      239.2       8.5827      2052.98184              7.36

   inflation_yoy  gold_return_1d  inr_change_1d  gold_inr_return_1d
0       6.814310             NaN            NaN                 NaN
1       6.239460        9.384023      -1.116937            8.162273
2       6.375839        8.095029       1.213407            9.406661
3       6.500000       -1.465201       3.133605            1.622490
4       7.142857       -1.197852       1.390431            0.175924

In [63]:
master.head()

,date,price_usd,inr_per_usd,gold_price_inr,fed_intrest_rate,inflation_yoy,gold_return_1d,inr_change_1d,gold_inr_return_1d
0,1978-01-01,207.8,8.2010,1704.16780,6.70,6.814310,NaN,NaN,NaN
1,1978-02-01,227.3,8.1094,1843.26662,6.78,6.239460,9.384023,-1.116937,8.162273
2,1978-03-01,245.7,8.2078,2016.65646,6.79,6.375839,8.095029,1.213407,9.406661
3,1978-04-01,242.1,8.4650,2049.37650,6.89,6.500000,-1.465201,3.133605,1.622490
4,1978-05-01,239.2,8.5827,2052.98184,7.36,7.142857,-1.197852,1.390431,0.175924